<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.Wpf" Version="2.26.0" />
    <PackageReference Include="Microsoft.Azure.Kinect.BodyTracking" Version="1.1.2" />
    <PackageReference Include="Microsoft.Azure.Kinect.Sensor" Version="1.4.2" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(ProjectDir)assets&quot; &quot;$(ProjectDir)$(OutDir)assets&quot; /i /c /r /y" />
  </Target>

</Project>
